// Standardized mock book data for tests and UI
export const MOCK_BOOKS = [
  {
    id: '1',
    title: 'The Pragmatic Programmer',
    authorName: 'Andrew Hunt',
    description: 'Your Journey to Mastery',
    price: 39.99,
    category: 'Technology',
    rating: 4.8,
    thumbnail: 'https://i.postimg.cc/2636YCFZ/book12.png',
    isFeatured: true,
    hasOffer: false,
    isPopular: true,
    isFavorite: true,
    isOwned: false,
  },
  {
    id: '2',
    title: 'Atomic Habits',
    authorName: 'James Clear',
    description: 'Build Good Habits & Break Bad Ones',
    price: 25.5,
    category: 'Self-Help',
    rating: 4.7,
    thumbnail: 'https://i.postimg.cc/MTXTwzbR/book14.png',
    isFeatured: true,
    hasOffer: true,
    isPopular: true,
    isFavorite: false,
    isOwned: true,
  },
  {
    id: '3',
    title: 'Deep Work',
    authorName: 'Cal Newport',
    description: 'Rules for Focused Success',
    price: 30.0,
    category: 'Productivity',
    rating: 4.6,
    thumbnail: 'https://i.postimg.cc/nzMzxnYB/book15-1.png',
    isFeatured: false,
    hasOffer: true,
    isPopular: false,
    isFavorite: true,
    isOwned: false,
  },
  {
    id: '4',
    title: 'The Lean Startup',
    authorName: 'Eric Ries',
    description: 'Continuous Innovation',
    price: 28.75,
    category: 'Business',
    rating: 4.5,
    thumbnail: 'https://i.postimg.cc/bJdJPqHQ/book16-1.png',
    isFeatured: true,
    hasOffer: false,
    isPopular: false,
    isFavorite: false,
    isOwned: true,
  },
  {
    id: '5',
    title: 'Zero to One',
    authorName: 'Peter Thiel',
    description: 'Notes on Startups',
    price: 22.99,
    category: 'Business',
    rating: 4.4,
    thumbnail: 'https://i.postimg.cc/W16t6W1T/book3-4-2.png',
    isFeatured: false,
    hasOffer: true,
    isPopular: true,
    isFavorite: false,
    isOwned: false,
  },
  {
    id: '6',
    title: 'Educated',
    authorName: 'Tara Westover',
    description: 'A Memoir',
    price: 19.99,
    category: 'Biography',
    rating: 4.3,
    thumbnail: 'https://i.postimg.cc/mrmDKPMz/book3-4.png',
    isFeatured: false,
    hasOffer: false,
    isPopular: false,
    isFavorite: true,
    isOwned: true,
  },
  {
    id: '7',
    title: 'Sapiens',
    authorName: 'Yuval Noah Harari',
    description: 'A Brief History of Humankind',
    price: 35.0,
    category: 'History',
    rating: 4.9,
    thumbnail: 'https://i.postimg.cc/JhpnSsJH/book4-4.png',
    isFeatured: true,
    hasOffer: false,
    isPopular: true,
    isFavorite: false,
    isOwned: false,
  },
  {
    id: '8',
    title: 'The Alchemist',
    authorName: 'Paulo Coelho',
    description: 'A Fable About Following Your Dream',
    price: 18.5,
    category: 'Fiction',
    rating: 4.2,
    thumbnail: 'https://i.postimg.cc/XJXJWncY/book5-4.png',
    isFeatured: false,
    hasOffer: true,
    isPopular: false,
    isFavorite: true,
    isOwned: true,
  },
  {
    id: '9',
    title: 'Thinking, Fast and Slow',
    authorName: 'Daniel Kahneman',
    description: 'Explores Two Modes of Thought',
    price: 27.0,
    category: 'Psychology',
    rating: 4.6,
    thumbnail: 'https://i.postimg.cc/qRgRrpXq/book6-1.png',
    isFeatured: true,
    hasOffer: false,
    isPopular: true,
    isFavorite: false,
    isOwned: false,
  },
  {
    id: '10',
    title: 'Start With Why',
    authorName: 'Simon Sinek',
    description: 'How Great Leaders Inspire',
    price: 24.99,
    category: 'Business',
    rating: 4.5,
    thumbnail: 'https://i.postimg.cc/XJXJWncX/book7-1.png',
    isFeatured: false,
    hasOffer: true,
    isPopular: false,
    isFavorite: true,
    isOwned: true,
  },
  {
    id: '11',
    title: 'Grit',
    authorName: 'Angela Duckworth',
    description: 'The Power of Passion and Perseverance',
    price: 21.5,
    category: 'Self-Help',
    rating: 4.3,
    thumbnail: 'https://i.postimg.cc/Kz4zbmr1/book8-1.png',
    isFeatured: true,
    hasOffer: false,
    isPopular: true,
    isFavorite: false,
    isOwned: false,
  },
  {
    id: '12',
    title: 'Drive',
    authorName: 'Daniel H. Pink',
    description: 'What Motivates Us',
    price: 23.0,
    category: 'Business',
    rating: 4.4,
    thumbnail: 'https://i.postimg.cc/G292RbJ8/book9-1.png',
    isFeatured: false,
    hasOffer: true,
    isPopular: false,
    isFavorite: true,
    isOwned: true,
  },
];
